import { Card } from '@/redux/features/gameSlice';

const demoCards:  Card[] = [
  {
    number: -1,
    hash: 'hash_1',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_1',
  },
  {
    number: -1,
    hash: 'hash_2',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_2',
  },
  {
    number: -1,
    hash: 'hash_3',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_3',
  },
  {
    number: -1,
    hash: 'hash_4',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_4',
  },
  {
    number: -1,
    hash: 'hash_5',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_5',
  },
  {
    number: -1,
    hash: 'hash_6',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_6',
  },
  {
    number: -1,
    hash: 'hash_7',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_7',
  },
  {
    number: -1,
    hash: 'hash_8',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_8',
  },
  {
    number: -1,
    hash: 'hash_9',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_9',
  },
  {
    number: -1,
    hash: 'hash_10',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_10',
  },
  {
    number: -1,
    hash: 'hash_11',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_11',
  },
  {
    number: -1,
    hash: 'hash_12',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_12',
  },
  {
    number: -1,
    hash: 'hash_13',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_13',
  },
  {
    number: -1,
    hash: 'hash_14',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_14',
  },
  {
    number: -1,
    hash: 'hash_15',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_15',
  },
  {
    number: -1,
    hash: 'hash_16',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_16',
  },
  {
    number: -1,
    hash: 'hash_17',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_17',
  },
  {
    number: -1,
    hash: 'hash_18',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_18',
  },
  {
    number: -1,
    hash: 'hash_19',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_19',
  },
  {
    number: -1,
    hash: 'hash_20',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_20',
  },
  {
    number: -1,
    hash: 'hash_21',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_21',
  },
  {
    number: -1,
    hash: 'hash_22',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_22',
  },
  {
    number: -1,
    hash: 'hash_23',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_23',
  },
  {
    number: -1,
    hash: 'hash_24',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_24',
  },
  {
    number: -1,
    hash: 'hash_25',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_25',
  },
  {
    number: -1,
    hash: 'hash_26',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_26',
  },
  {
    number: -1,
    hash: 'hash_27',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_27',
  },
  {
    number: -1,
    hash: 'hash_28',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_28',
  },
  {
    number: -1,
    hash: 'hash_29',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_29',
  },
  {
    number: -1,
    hash: 'hash_30',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_30',
  },
  {
    number: -1,
    hash: 'hash_31',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_31',
  },
  {
    number: -1,
    hash: 'hash_32',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_32',
  },
  {
    number: -1,
    hash: 'hash_33',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_33',
  },
  {
    number: -1,
    hash: 'hash_34',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_34',
  },
  {
    number: -1,
    hash: 'hash_35',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_35',
  },
  {
    number: -1,
    hash: 'hash_36',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_36',
  },
  {
    number: -1,
    hash: 'hash_37',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_37',
  },
  {
    number: -1,
    hash: 'hash_38',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_38',
  },
  {
    number: -1,
    hash: 'hash_39',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_39',
  },
  {
    number: -1,
    hash: 'hash_40',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_40',
  },
  {
    number: -1,
    hash: 'hash_41',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_41',
  },
  {
    number: -1,
    hash: 'hash_42',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_42',
  },
  {
    number: -1,
    hash: 'hash_43',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_43',
  },
  {
    number: -1,
    hash: 'hash_44',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_44',
  },
  {
    number: -1,
    hash: 'hash_45',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_45',
  },
  {
    number: -1,
    hash: 'hash_46',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_46',
  },
  {
    number: -1,
    hash: 'hash_47',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_47',
  },
  {
    number: -1,
    hash: 'hash_48',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_48',
  },
  {
    number: -1,
    hash: 'hash_49',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_49',
  },
  {
    number: -1,
    hash: 'hash_50',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_50',
  },
  {
    number: -1,
    hash: 'hash_51',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_51',
  },
  {
    number: -1,
    hash: 'hash_52',
    isFreeReveal: false,
    guessedNumbers: [],
    status: 'hidden',
    _id: 'id_52',
  },
];

export default demoCards;
