import { PropsWithChildren } from 'react';
import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import Layout from '@/components/Layout';
import ConnectKit from '@/providers/ConnectKit';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConnectKit>
          <Layout>{children}</Layout>
        </ConnectKit>
      </body>
    </html>
  );
}
